"""
LLM-as-Judge for Quality Evaluation.

This module uses a separate LLM call to evaluate the quality of the agent's final response
based on the user's request and the tools that were used.
"""

import logging
import json
from typing import Dict, Any, List, Optional

from mcp_host.llm_provider import LLMManager
from mcp_host.prompt_service import prompt_library

logger = logging.getLogger(__name__)

class QualityGate:
    """
    A class to evaluate the quality of an agent's response using an LLM-as-judge.
    """

    def __init__(self, llm_manager: LLMManager):
        self.llm_manager = llm_manager

    async def evaluate(
        self,
        user_message: str,
        tool_calls: List[Dict[str, Any]],
        final_response: str,
        trace_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Evaluates the quality of the agent's response.

        Args:
            user_message: The original message from the user.
            tool_calls: A list of tool calls made by the agent.
            final_response: The final response generated by the agent.
            trace_id: The trace ID for logging and tracking.

        Returns:
            A dictionary containing the quality score and justification, or None on failure.
        """
        trace_id = trace_id or "quality_gate"
        logger.info(f"[{trace_id}] ⚖️ Evaluating agent response quality...")

        try:
            prompt = prompt_library.get_prompt(
                "quality_gate_eval",
                user_message=user_message,
                tool_calls=json.dumps(tool_calls, indent=2),
                final_response=final_response,
            )

            raw_eval = await self.llm_manager.generate(
                prompt=prompt,
                max_tokens=256,
                temperature=0.0,
                trace_id=trace_id,
            )

            # The LLM is instructed to return JSON, so we parse it.
            eval_result = json.loads(raw_eval)

            if "quality_score" in eval_result and "justification" in eval_result:
                logger.info(f"[{trace_id}] ✅ Quality evaluation successful: Score={eval_result['quality_score']}")
                return eval_result
            else:
                logger.warning(f"[{trace_id}] ⚠️ Quality evaluation response is missing required keys.")
                return None

        except json.JSONDecodeError:
            logger.error(f"[{trace_id}] ❌ Failed to parse LLM response as JSON in quality gate.")
            return None
        except Exception as e:
            logger.error(f"[{trace_id}] ❌ An unexpected error occurred during quality evaluation: {e}", exc_info=True)
            return None

# Singleton instance
# This will be initialized properly in the main application context where the llm_manager is available.
quality_gate: Optional[QualityGate] = None

def initialize_quality_gate(llm_manager: LLMManager):
    """Initializes the singleton quality_gate instance."""
    global quality_gate
    if quality_gate is None:
        quality_gate = QualityGate(llm_manager)
        logger.info("✅ QualityGate initialized.")

